### ISSUE TITLE
CPL File

### ISSUE THREAD

**Issue by slimline33** [CoretechR/Keybon#14]
Hi Max,

I hope this message finds you well! I just discovered your project today, and I must say, it’s absolutely fantastic—great work!

Would it be possible for you to provide a CPL file for JLCPCB? This would allow us to have most of the components pre-assembled, saving time and effort.

Thank you in advance for your help, and please let me know if you need any additional details!

Best regards,

Christoph

**Comment by CoretechR** [comment]
Hi Christoph, 
I don't really have experience with generating CPL files in EAGLE since all my EAGLE board have been hand assembled.
But I found this guide by JLCPCB: https://jlcpcb.com/help/article/How-to-generate-BOM-and-CPL-from-Eagle-CAD-automatically
So here are the files created by the ULP script:

[Keybon REV 1.1_top_cpl.csv](https://github.com/user-attachments/files/17835572/Keybon.REV.1.1_top_cpl.csv)
[Keybon REV 1.1_top_bom.csv](https://github.com/user-attachments/files/17835573/Keybon.REV.1.1_top_bom.csv)

I have no way of checking if these are correct so you should definitely be careful and double-check everything with the BOM.

**Comment by slimline33** [comment]
thanks! That will help!

**Comment by slimline33** [comment]
![dc2f27b6-04fc-4fbb-8485-76dcfa22af7c](https://github.com/user-attachments/assets/7103f086-e781-42fc-81ed-5af7d8e6fd77)

"Yes, definitely double-check! 😊 The F1 fuse selected by JLCPCB isn't the correct part, but it's no problem—I can solder it by hand. I paid €65 for 5 boards, including shipping and taxes, without the OLED.

I think the price is really fair."
